name: Integration Evals

on:
  push:
    branches: [main, trunk, master]
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          uv venv
          . .venv/bin/activate
          uv pip install -e .[test]
      - name: Run integration evals
        env:
          FIREWORKS_API_KEY: ${{ secrets.FIREWORKS_API_KEY }}
        run: |
          . .venv/bin/activate
          pytest -q -m integration --maxfail=1
